import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "./components/SideBar";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className="min-h-screen flex flex-col md:flex-row"
      >
        {/*Side bar fijo paginas grandes */}
        <div className="hidden md:block w-64 bg-blue-700
        text-white">
          <SideBar/>
        </div>
        {/*Contenido ppal*/}
        <div className="flex-1 flex flex-col">
          {/*Side bar movil*/}
          <div className="md:hidden p-2">
            <SideBar/>
          </div>
          <Header/>
          <main className="flex-1 p-6 bg-gray-100">
            {children}
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
